[greeter]
background = /etc/lightdm/background.jpg
default-user-image = /etc/lightdm/User_icon.png
bell = false
theme-name = Arc-Dark
icon-theme-name = Papirus-Dark
font-name = JetBrains Mono 10
clock-format = %a,  %b  %d, %Y   󰸘            %I:%M %p  󱑍 
