#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# To auto run startx on tty1 if no X display is running #
# [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec Hyprland
