#!/bin/sh

# .bashrc for root user

# history size and ignore duplicates
export HISTSIZE=-1
export HISTFILESIZE=-1
export HISTCONTROL="erasedups:ignorespace"

# export the terminal
export TERM=xterm-256color

# set editior nvim
export EDITOR="nvim"
export VISUAL="nvim"
