#!/bin/bash

# Disable bell
set bell-style none

# Color
set colored-stats on
set colored-completion-prefix on

# single tab to search and smartcase
set show-all-if-ambiguous on
set completion-ignore-case on
set page-completions off
set visible-stats on

# search in history by up and down key
"\e[A": history-search-backward
"\e[B": history-search-forward
