#!/usr/bin/env bash

# Change behaviours of command
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ls="ls --color=auto"
alias ip="ip -color=auto"
alias less="less -R"
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"

# Add new command
alias sqlite="sqlite3"
alias py="python"
alias la="ls -a"
alias ll="ls -lah"
alias l="ls -CF"
alias top="btop"
alias htop="btop"
alias nc="ncat"
alias lf="yazi"
alias neofetch="fastfetch"
alias batt="cat /sys/class/power_supply/BAT0/{capacity,status}"

# Neovim
alias nvim="nvim -p"
alias vi="nvim --noplugin"
alias vim="nvim --noplugin"
alias nfolder="nvim -c \"lua vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<leader>ff', true, false, true), 'm', false)\""

# Develop env
alias mesonsetup="meson setup --buildtype release --reconfigure build"
alias mesonbuild="meson compile -C build"
alias cmakesetup="cmake -S . -B build -G Ninja"
alias cmakebuild="cmake --build build"
alias gitlog="git log --all --parents --graph --decorate --oneline"

# Soruces

# Arch env
source "${HOME}/.config/shell/alias/arch_env_alias"

# Assembly
source "${HOME}/.config/shell/alias/asm_alias"

# Fzf
source "${HOME}/.config/shell/alias/fzf_alias"

# Multimedia utils
source "${HOME}/.config/shell/alias/multimedia_alias"

# Tmux
# source "${HOME}/.config/shell/alias/tmux_alias"
