#!/bin/sh

# Aliases:

# Change behaviours of command
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias batt="bat --mouse"
alias ls="ls --color=auto"
alias ip="ip -color=auto"
alias less="less -R"
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
alias delta="delta --line-numbers"
alias fzf="fzf --ansi"

# Add new command
alias py="python"
alias la="ls -a"
alias ll="ls -lah"
alias l="ls -CF"
alias top="btop"
alias htop="btop"
alias fz="fzf --height=85% --layout=reverse"
alias lf="yazi"
alias batt="cat /sys/class/power_supply/BAT0/capacity"
alias fzp="fz --preview 'bat --style=numbers --color=always {}'"
alias fzfp="fzf --preview 'bat --style=numbers --color=always {}'"
alias hisr="history | fz"
alias his="history | fz --tac"
alias exa="eza"
alias tree="eza -la --git --tree"
alias vi="nvim --noplugin"
alias vim="nvim --noplugin"
alias neofetch="fastfetch"
alias gitlog="git log --parents --graph --decorate"

# Tmux
alias tml="tmux ls"
alias tmd="tmux detach-client"
alias tmda="tmux kill-server"
alias tmds="tmux kill-session -t"
alias tmdo="tmux kill-session -a"

# flutter on emulator
alias futtu="tmux kill-session -t 'flutter'; tmux new-session -s 'flutter' -d 'emulator -avd my_avd' \; split-window -h 'sleep 7 && flutter run' \; attach"
alias futturl="tmux send-keys -t 'flutter' r"
alias futtukill="tmux kill-session -t 'flutter'"

# Default Qemu command
alias defqemu="qemu-system-x86_64 --enable-kvm -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/x64/OVMF_CODE.4m.fd -cpu host -smp 4 -m 4G -display sdl,gl=on -vga virtio"

# Reduce img size by conversion by ffmpeg
# for file in *.{jpg,jpeg,png};do ffmpeg -i $file -y "${file%.*}.jpg" ; done

# Functions

condaactivate() {
	conda_env="pytorch"
	[ -z "$1" ] || conda_env=$1
	conda_env="${conda_env}_env"
	source ~/miniconda3/etc/profile.d/conda.sh && conda activate "${conda_env}"
}

# Function to attach tmux at given directory
tma() {
	[ -z "$1" ] || cd "$1" || exit
	tmux_id=$(pwd | sed 's/\./_/g')
	if [ -n "$TMUX" ]; then
		tmux switch-client -t "$tmux_id"
	else
		tmux new-session -s "$tmux_id" || tmux attach -t "$tmux_id"
	fi
}

# Go to the location where tmux server is made
tmc() {
	cd "$(tmux display-message -p '#{session_name}')" || exit
}

# Go to the location with fzf
fcd() {
	cd "$(fd -t d | fz)" || exit
}

# Record screen without audio
scrrec() {
	Output_Video=Recording-$(date +%F_%T).mp4
	[ -z "${1}" ] || Output_Video="${1}"
	wf-recorder -g "$(slurp)" -f ~/Pictures/Recordings/"${Output_Video}"
}

# Record screen microphone audio
scrrecmicaudio() {
	Output_Video=Recording-$(date +%F_%T).mp4
	[ -z "${1}" ] || Output_Video="${1}"
	wf-recorder -g "$(slurp)" -a -f ~/Pictures/Recordings/"${Output_Video}"
}

# Record screen output audio
scrrecoutaudio() {
	Output_Video=Recording-$(date +%F_%T).mp4
	[ -z "${1}" ] || Output_Video="${1}"
	wf-recorder -g "$(slurp)" --audio=alsa_output.pci-0000_06_00.6.analog-stereo.monitor -f ~/Pictures/Recordings/"${Output_Video}"
}
