;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;   The README contains a lot of information
;

;==========================================================


[bar/main]
width = 100%
height = 30px
radius = 0
dpi = 96

background = #111122
foreground = #99aaaa
line-size = 3pt
border-size = 0pt
border-color = #00000000
padding-left = 2
padding-right = 3
module-margin = 2
separator = |
separator-foreground = #2b3338

font-0 = JetBrains Mono:style=Medium:size=10;1
font-1 = JetBrainsMono Nerd Font:style=Medium:size=14;2
font-2 = JetBrainsMono Nerd Font:style=Medium:size=11;3

modules-left = menu xworkspaces cpu memory filesystem
modules-center = xwindow
modules-right = systray eth wlan battery date time sysmenu
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true



[module/systray]
type = internal/tray
format-margin = 8pt
tray-spacing = 16pt
tray-size = 40%

[module/menu]
type    = custom/text
label            =  
format-font		= 2
format-foreground = #4dd0e1
content-padding    = 1
click-left         = rofi -show drun -theme ~/.config/rofi/config.rasi
click-right        = rofi -show window -theme ~/.config/rofi/config.rasi


; [module/sep]
; type = custom/text
; content = |
; content-foreground = #3c4449


[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true
enable-click = true
format-font		= 3
format = <label-state>
; 󰙱  󰙲    󰌠  󰲒  󱘗 󰬷      󰎙 󰌛  󰪮          󰌟  󰣀 
;   󰊯         󰀹 󰈌 󰓓   󰈸    󱐌   󰖗 󰖐   󱐋 󱩎     
;                                   
;                              󰳭 󰕼 󰍯 󰓃 
;        󰮠   󰊤   󰺷 󰍳 󰊗 󱎓 󰸶 󰊖 󰝆 󰈎   󰋀 󰗵 󰠥 󰗹 󱐡 󰥟  󰒱 󰷚 
;  󰉔   󰙯 󰝚 󰽰 󰀂 󰯡 󰈁 󰈂    󰘚 󱤓      󰕓  󱊟 󱇰 󱊞   󰣐  󰍹 󰂯  

; icon-0 = 1; 
; icon-1 = 2; 
; icon-2 = 3;
; icon-3 = 4; 
; icon-4 = 5;
; icon-5 = 6; 
; icon-6 = 7; 
; icon-7 = 8;󰙯
; icon-8 = 9;
icon-0 = 1;
icon-1 = 2; 
icon-2 = 3;
icon-3 = 4; 
icon-4 = 5;
icon-5 = 6; 
icon-6 = 7; 
icon-7 = 8; 
icon-8 = 9; 
icon-default = 

label-active = %icon%
label-active-foreground = #009999
label-active-padding = 1 

label-occupied = %icon%
label-occupied-foreground = #b998d0
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-background = #f38ba8
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = #282738
label-empty-padding = 1


[module/xwindow]
type = internal/xwindow
label = %title:0:40:...%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-font		= 2
format-prefix-foreground = #a8a133
label = %percentage:2%%


[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-font		= 2
format-prefix-foreground = #009189
label = %percentage_used:2%%


[module/filesystem]
type = internal/fs
interval = 25
mount = /
format-mounted-prefix = " "
format-prefix-font		= 2
format-mounted-prefix-foreground = #ec407a
label-mounted=  %free%/%total%


[module/wlan]
type = internal/network
interface-type = wireless
interval = 5
format-connected-prefix = "󰀂 "
format-connected-prefix-font		= 2
format-connected-prefix-foreground = #61c766
label-connected =  %signal%% %essid%
label-disconnected = "󰯡 "
label-disconnected-font = 2
label-disconnected-foreground = #772222

[module/eth]
type = internal/network
interface-type = wired
interval = 5
format-connected-prefix = "󰈁 "
format-connected-prefix-font		= 2
format-connected-prefix-foreground = #61c766
label-connected = %linkspeed%
label-disconnected = 󰈂
label-disconnected-font = 2
label-disconnected-foreground = #772222


[module/date]
type = internal/date
interval = 60
format-prefix = "󰸘 "
format-prefix-font		= 2
format-prefix-foreground = #e57c46
date = %a, %b %d, %Y
label = %date%

[module/time]
type = internal/date
interval = 20
format-prefix = "󱑍 "
format-prefix-font		= 2
format-prefix-foreground = #e57c46
time = %I:%M %p
label = %time%


[module/battery]
type = internal/battery
full-at = 99
battery = BAT0
adapter = AC
poll-interval = 3
format-charging            = <ramp-capacity>󱐌<label-charging>
format-discharging		   = <ramp-capacity> <label-discharging>
label-charging             = %percentage%%
label-discharging		   = %percentage%%
label-charging-padding     = 1
ramp-capacity-foreground = #6c77bb
ramp-capacity-font = 2
ramp-capacity-0 = 󱃍
ramp-capacity-1 = 󱊡
ramp-capacity-2 = 󱊢
ramp-capacity-3 = 󱊢
ramp-capacity-4 = 󱊣


[module/sysmenu]
type = custom/text
label = ⏻
format-foreground = #4dd0e1
format-font = 2
click-left = ~/.config/rofi/powermenu.sh



[settings]
screenchange-reload = true
pseudo-transparency = true
