require("nvimprof")

vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set noswapfile")
vim.cmd("set autoindent")
vim.cmd("set smartindent")
vim.cmd("set mouse=a")
vim.cmd("set showcmd")
vim.cmd("set shiftwidth=4")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set smartcase")
vim.cmd("set ignorecase")
vim.cmd("set showmatch")
vim.cmd("set wrap")
vim.cmd("set linebreak")
vim.cmd("set title")
vim.cmd("set scrolloff=10")
vim.cmd("syntax on")
vim.cmd("filetype on")
vim.cmd("set guicursor=n-v-c-sm:block")
vim.cmd("set guicursor+=i-ci-ve:hor20")
vim.cmd("set guicursor+=r-cr-o:ver25")
vim.cmd("set cursorline")
