;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;   The README contains a lot of information
;

;==========================================================
;
; 󰙱  󰙲    󰌠  󰲒  󱘗 󰬷      󰎙 󰌛  󰪮          󰌟  󰣀 
;   󰊯         󰀹 󰈌 󰓓   󰈸    󱐌   󰖗 󰖐   󱐋 󱩎     
;                                   
;                              󰳭 󰕼 󰍯 󰓃 
;        󰮠   󰊤   󰺷 󰍳 󰊗 󱎓 󰸶 󰊖 󰝆 󰈎   󰋀 󰗵 󰠥 󰗹 󱐡 󰥟  󰒱 󰷚 
;  󰉔   󰙯 󰝚 󰽰 󰀂 󰯡 󰈁 󰈂    󰘚 󱤓      󰕓  󱊟 󱇰 󱊞   󰣐  󰍹 󰂯  
;


[bar/main]
width = 100%
height = 25px
radius = 10px
dpi = 96

foreground = #cdd5f4
background = #15121b00
#background-0 = #15121b00
#background-0 = #1e1e2e
line-size = 3pt
border-size = 10px
padding-left = 5px
padding-right = 5px
# module-margin = 5px
separator = |
separator-foreground = #2b3338
separator-background = #1e1e2e

font-0 = JetBrains Mono:style=Bold:size=10;1
font-1 = JetBrainsMono Nerd Font:style=Bold:size=14;2
font-2 = JetBrainsMono Nerd Font:style=Bold:size=11;3

modules-left = xworkspaces cpu memory filesystem
modules-center = xwindow
modules-right = systray eth wlan battery date time
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true


[module/systray]
type = internal/tray
# format-margin = 8pt
tray-padding = 5pt
tray-spacing = 16pt
tray-size = 60%
format-background = #1e1e2e

[module/menu]
type    = custom/text
label            =  
format-font		= 2
format-foreground = #4dd0e1
format-background = #1e1e2e
content-padding    = 1
click-left         = rofi -show drun -theme ~/.config/rofi/config.rasi
click-right        = rofi -show window -theme ~/.config/rofi/config.rasi

# [module/sysmenu]
# type = custom/text
# label = ⏻
# format-padding = 5px
# format-foreground = #4dd0e1
# format-background = #1e1e2e
# format-font = 2
# click-left = sh ~/.config/rofi/powermenu.sh


[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true
enable-click = true
format-font = 3
format = <label-state>
label = %icon%
format-padding = 5px
label-empty-padding = 5px
label-active-padding = 5px
label-urgent-padding = 5px
label-occupied-padding = 5px
label-empty-foreground = #282738
label-active-foreground = #78cde8
label-urgent-background = #f38ba8
label-occupied-foreground = #525466
format-background = #1e1e2e
# icon-0 = 1;
# icon-1 = 2;
# icon-2 = 3;
# icon-3 = 4;
# icon-4 = 5;
# icon-5 = 6;
# icon-6 = 7;
# icon-7 = 8;
# icon-8 = 9;
# icon-default = 



[module/xwindow]
type = internal/xwindow
label = %title:0:40:...%
format-padding = 5px
format-background = #1e1e2e

[module/cpu]
type = internal/cpu
interval = 2
format-padding = 5px
format-prefix = " "
format-prefix-font		= 2
format-prefix-foreground = #a8a133
format-background = #1e1e2e
label = %percentage:2%%


[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-padding = 5px
format-prefix-font		= 2
format-prefix-foreground = #009189
format-background = #1e1e2e
label = %percentage_used:2%%


[module/filesystem]
type = internal/fs
interval = 25
mount = /
format-mounted-prefix = " "
format-prefix-font		= 2
format-padding = 5px
format-mounted-prefix-foreground = #ec407a
format-mounted-background = #1e1e2e
label-mounted=  %free%/%total%


[module/wlan]
type = internal/network
interface-type = wireless
interval = 5
format-padding = 5px
format-connected-prefix = "󰀂 "
format-connected-prefix-font		= 2
format-connected-prefix-foreground = #61c766
format-connected-background = #1e1e2e
format-disconnected-background = #1e1e2e
label-connected =  %signal%% %essid%
label-disconnected = "󰯡 "
label-disconnected-font = 2
label-disconnected-foreground = #772222

[module/eth]
type = internal/network
interface-type = wired
interval = 5
format-padding = 5px
format-connected-prefix = "󰈁 "
format-connected-prefix-font		= 2
format-connected-prefix-foreground = #61c766
format-connected-background = #1e1e2e
format-disconnected-background = #1e1e2e
label-connected = %linkspeed%
label-disconnected = 󰈂
label-disconnected-font = 2
label-disconnected-foreground = #772222


[module/date]
type = internal/date
interval = 60
format-prefix = "󰸘 "
format-padding = 5px
format-prefix-font		= 2
format-prefix-foreground = #e57c46
format-background = #1e1e2e
date = %a, %b %d, %Y
label = %date%

[module/time]
type = internal/date
interval = 20
format-padding = 5px
format-prefix = "󱑍 "
format-prefix-font		= 2
format-prefix-foreground = #e57c46
format-background = #1e1e2e
time = %I:%M %p
label = %time%


[module/battery]
type = internal/battery
full-at = 99
battery = BAT0
adapter = AC
poll-interval = 3
format-padding = 5px
format-charging-background = #1e1e2e
format-discharging-background = #1e1e2e
format-charging            = <ramp-capacity>󱐌<label-charging>
format-discharging		   = <ramp-capacity> <label-discharging>
label-charging             = %percentage%%
label-discharging		   = %percentage%%
label-charging-padding     = 1
ramp-capacity-foreground = #6c77bb
ramp-capacity-font = 2
ramp-capacity-0 = 󱃍
ramp-capacity-1 = 󱊡
ramp-capacity-2 = 󱊢
ramp-capacity-3 = 󱊢
ramp-capacity-4 = 󱊣


[global/wm]
margin-bottom = 30px
margin-top = 30px


[settings]
screenchange-reload = true
pseudo-transparency = true
